VERSION_MONIKER = "Pocket Arcade"
VERSION_MAJOR   = 1
VERSION_MINOR   = 0
VERSION_PATCH   = 0

VERSION_STRING = f"{VERSION_MONIKER} {VERSION_MAJOR}.{VERSION_MINOR}.{VERSION_PATCH}"

print(VERSION_STRING)